
services:
  server:
    image: quickit-server
    pull_policy: never
    container_name: quickit-server
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    env_file: 
      - ./.env
    depends_on: 
      - db

  client:
    image: quickit-client
    pull_policy: never
    container_name: quickit-client
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: runner
    ports: 
      - "8080:80"
    env_file: 
      - ./.env
    depends_on: 
      - server
    
  db:
    image: postgres:17
    container_name: quickit-postgres
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
